modLoader="lowcodefml"
loaderVersion="[4,)"
license="MIT"
showAsResourcePack=false

[[mods]]
modId="create_nerfad"
version="1.2.3-neoforge+mc1.21.1"
displayName="Create: Not Enough Resources For A Dummy"
description="Adds the original server's Create processing recipes."
authors="Konitor"

[[dependencies.create_nerfad]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.create_nerfad]]
modId="neoforge"
type="required"
versionRange="[21.1.241,21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.create_nerfad]]
modId="create"
type="required"
versionRange="[6.0.10,6.0.11)"
ordering="AFTER"
side="BOTH"

[[dependencies.create_nerfad]]
modId="backport"
type="required"
versionRange="[1.5,1.6)"
ordering="AFTER"
side="BOTH"
