@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.github.ysbbbbbb.kaleidoscopetavern.network.message;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;