plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.95'
}

group = mod_group_id
version = mod_version

base {
    archivesName = 'recipe-set-diagnostic'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

tasks.withType(ProcessResources).configureEach {
    def replacements = [
            minecraft_version_range: minecraft_version_range,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replacements
    filesMatching('META-INF/neoforge.mods.toml') {
        expand replacements
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
