#Create Aeronautics Toolgun Client Settings
#Sat Jul 18 17:54:39 CST 2026
autoWeldEnabled=false
bearingAxisMode=AUTO
bearingAxisVisualsEnabled=true
connectedSublevelProximity=0.5
connectionMode=BEARING
deleteRange=8
hudEnabled=true
magneticMarkersEnabled=true
nearbyQueryRange=64
offsetX=0
offsetY=0
offsetZ=0
panel=TOOLS
previewEnabled=true
rangeDeleteEnabled=false
rotationDegrees=0
rotationStep=15
scalePercent=100
selectedFile=
snapMode=LEGACY
translateStep=0.25
weldAdjustStep=0.25
weldSelectionMode=FREE
