@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.github.ysbbbbbb.kaleidoscopetavern.datagen.builder;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;